trigger:
 - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'pipelines-backend'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile