  substitutions:
    _REGION: asia-southeast2
  steps:
  - name: 'gcr.io/k8s-skaffold/skaffold'
    entrypoint: 'sh'
    args:
    - -xe
    - -c
    - |
      # Build and push images
      skaffold build --file-output=/workspace/artifacts.json \
                    --default-repo=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/backend-kafe \
                    --push=true

      # Test images
      skaffold test --build-artifacts=/workspace/artifacts.json

  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
    - -xe
    - -c
    - |
      gcloud config set deploy/region ${_REGION}
      sed -i s/PROJECT_ID/$PROJECT_ID/g deploy/*
      gcloud deploy apply --file deploy/clouddeploy.yaml
      gcloud deploy apply --file deploy/staging.yaml
      gcloud deploy apply --file deploy/prod.yaml
      gcloud deploy releases create rel-${SHORT_SHA} \
                          --delivery-pipeline pipeline-backend \
                          --description "$(git log -1  --pretty='%s')" \
                          --build-artifacts /workspace/artifacts.json \
                          --annotations "commit_ui=https://source.cloud.google.com/$PROJECT_ID/github_veapee_backend-kafe/+/$COMMIT_SHA"

  images:
  - '${_REGION}-docker.pkg.dev/kafe-tabebuya/cloud-run-source-deploy/backend-kafe/backend-kafe:$COMMIT_SHA'