apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: backend-kafe
spec:
 template:
  spec:
   containers:
   - image: asia-southeast2-docker.pkg.dev/kafe-tabebuya/cloud-run-source-deploy/backend-kafe/backend-kafe:$COMMIT_SHA