apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: kafe-pipeline
  labels:
    app: kafe-pipeline
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: staging
    profiles:
    - staging
  - targetId: prod
    profiles:
    - prod