apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prod
spec:
  template:
    spec:
      containers:
        - image: app
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                key: latest
                name: MONGO_URI
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                key: latest
                name: NODE_ENV
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: latest
                name: JWT_SECRET
          - name: EMAIL_HOST
            valueFrom:
              secretKeyRef:
                key: latest
                name: EMAIL_HOST
          - name: EMAIL_USER
            valueFrom:
              secretKeyRef:
                key: latest
                name: EMAIL_USER
          - name: EMAIL_PASS
            valueFrom:
              secretKeyRef:
                key: latest
                name: EMAIL_PASS
          - name: CLOUDINARY_NAME
            valueFrom:
              secretKeyRef:
                key: latest
                name: CLOUDINARY_NAME
          - name: CLOUDINARY_API_KEY
            valueFrom:
              secretKeyRef:
                key: latest
                name: CLOUDINARY_API_KEY
          - name: CLOUDINARY_SECRET
            valueFrom:
              secretKeyRef:
                key: latest
                name: CLOUDINARY_SECRET
