apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prod
requireApproval: true
spec:
  template:
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/backend-kafe:$COMMIT_SHA