apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: kafe-pipeline-staging
  annotations: {}
  labels: {}
description: kafe-pipeline-staging
requireApproval: true
run:
  location: projects/kafe-tabebuya/locations/asia-southeast2