apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: staging
run:
  location: projects/kafe-tabebuya/locations/asia-southeast2