apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: staging
spec:
  template:
    spec:
      containers:
      - image: asia-southeast2-docker.pkg.dev/kafe-tabebuya/cloud-run-source-deploy/backend-kafe/backend-kafe:$COMMIT_SHA